name: Build and Push timescaledb-pgrx Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "timescaledb-pgrx/**"
      - ".github/workflows/timescaledb-pgrx.yaml"
  schedule:
    # Run at 10:00 AM UTC+3
    - cron: "0 7 * * 1"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      image-name: ${{ secrets.DOCKERHUB_USERNAME }}/timescaledb-pgrx
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get current date (YYYYMMDD)
        id: date
        run: echo "ymd=$(date -u +'%Y%m%d')" >> "$GITHUB_OUTPUT"

      - id: setup-buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        env:
          DOCKER_BUILDKIT: 1
        with:
          context: ./timescaledb-pgrx
          push: true
          tags: |
            ${{ env.image-name }}:latest
            ${{ env.image-name }}:${{ github.sha }}
            ${{ env.image-name }}:${{ steps.date.outputs.ymd }}
          cache-from: type=registry,ref=${{ env.image-name }}:buildcache
          cache-to: type=registry,ref=${{ env.image-name }}:buildcache,mode=max
          builder: ${{ steps.setup-buildx.outputs.name }}
